

redis:
    host: '127.0.0.1'
    port: 6379
    db: 0
    prefix: 'biomaj'

rabbitmq:
    host: '127.0.0.1'
    port: 5672
    user: null
    password: null
    virtual_host: '/'

consul:
    host: null
    # Unique agent identifier name among biomaj downloaders
    id: 'biomaj_process_agent'

web:
    debug: true
    port: 5000
    local_endpoint: 'http://127.0.0.1:5000'

docker:
    # URL to connect to docker, use null if direct docker access, else put IP of the host (not localhost)
    url: 'tcp://127.0.0.1:2375'

tls:
    key: null
    cert: null

log_config:
    'version': 1
    'formatters':
        'generic':
            'format': '%(asctime)s %(levelname)-5.5s [%(name)s][%(threadName)s] %(message)s'
    'handlers':
        'console':
            'class': 'logging.StreamHandler'
            'formatter': 'generic'
            'level': 'DEBUG'
    'loggers':
        'root':
            'level': 'INFO'
            'handlers':
                - 'console'
        'biomaj':
            'level': 'DEBUG'
            'handlers':
                - 'console'
    'disable_existing_loggers': False
